trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
    publishWebProjects: true
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(51959a08-f28a-4ca0-bb0a-a1452e9bcbf6)'
    appType: 'webAppLinux'
    appName: 'dotnnet-web'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'
