trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
      - job: Build 
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              arguments: '--configuration $(buildConfiguration)'
            displayName: 'dotnet build $(buildConfiguration)'
          
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              arguments: '--configuration $(buildConfiguration)'
              publishWebProjects: true
            displayName: 'dotnet publish $(buildConfiguration)'

  - stage: docker
    jobs:
      - job: DockerBuildandPush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerconnect'
              repository: 'dotnet'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'

  - stage: DeployToTest
    jobs:
      - job: DeployToTest
        steps:
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'AzureAdoConnect'
              azureResourceGroup: 'aks_tf_naga_rg'
              kubernetesCluster: 'naga-aks-cluster'
              command: 'apply'
              useClusterAdmin: true
              namespace: 'test'
              arguments: '--timeout=10m'
              manifests: |
                manifestsAKS/deployment.yaml
                manifestsAKS/service.yaml
